### ISSUE TITLE
Hotspot crash on i386 Debian 6 when calling LinuxServicesDB.getServiceByName

### ISSUE THREAD

**Issue by sluukkonen** [jnr/jnr-netdb#1]
Some background:

I found about this after trying to upgrade one of our apps to JRuby 1.7.4, which uses jnr-netdb on operations like `Socket.getnameinfo`. Curiously, I cannot reproduce the crash on i386 Debian 7 or on any other system.

How to reproduce:

1. Install i386 Debian 6 to a virtual machine
2. Install Java & Maven (I tested this with both jdk7u40 and openjdk6 from debian repositories)
3. Run `mvn test`

Hotspot crash dump here: https://gist.github.com/sluukkonen/6599957

**Comment by headius** [comment]
We have not seen these issues reported again, so I'm closing. If these are still a problem, please reopen with reproduction.
